import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import React from "react";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import { CartProvider } from "@/shared/providers/CartProvider";
import { AppProvider } from "@/shared/providers/AppProvider";
import { BreadcrumbProvider } from "@/shared/providers/BreadcrumbProvider";
import LayoutWrapper from "@/components/layout-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <BreadcrumbProvider>
            <AppProvider>
              <LayoutWrapper>{children}</LayoutWrapper>
            </AppProvider>
          </BreadcrumbProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
